### ISSUE TITLE
Arduino 1.6.6: 'namespaceArduinoJson' does not name a type

### ISSUE THREAD

**Issue by bblanchon** [bblanchon/ArduinoJson#157]
When compiling the examples on Arduino 1.6.6 on Windows, there is the following error:

```
JsonGeneratorExample:9: error: 'namespaceArduinoJson' does not name a type
```

**Comment by bblanchon** [comment]
It's a [known bug](JsonGeneratorExample:9: error: 'namespaceArduinoJson' does not name a type) in Arduino 1.6.6.

The solution is to roll back to 1.6.5 or use the hourly build.

**Comment by domonetic** [comment]
any solution?

**Comment by bblanchon** [comment]
As I said, for now you have to go back to 1.6.5 or download the [hourly build](http://www.arduino.cc/en/Main/Software#hourly).

**Comment by domonetic** [comment]
yes, in hourly build run fine.

**Comment by bblanchon** [comment]
Fixed in Arduino 1.6.7

**Comment by gsalvati** [comment]
Still the same problem for me:

SRC:
JsonObject& deviceObj = jsonBuffer.createObject();
deviceObj["type"] = "switch";

Error:
error: 'deviceObj' does not name a type
 deviceObj["type"] = "switch";
 ^
exit status 1
'deviceObj' does not name a type

**Comment by bblanchon** [comment]
@gsalvati: I don't think it's related, can you please open a new issue and paste a bit more code?

**Comment by gsalvati** [comment]
@bblanchon orry, I found the problem, deleted the post. My bad

**Comment by ksmiller99** [comment]
@gsalvati - what was the error and how was it resolved?
