### ISSUE TITLE
MsgPack 6.0.1-beta

### ISSUE THREAD

**Issue by trap98** [bblanchon/ArduinoJson#772]
Hey, i'm updating my project for use your new feature 'MsgPack', after 1 day i'm okay with the new API and i try to use this feature. I can serialize without any problem but when  I try to deserialize, and serialize in json format this time, my json is empty. I think i don't understand the API or idk, someone can help me ? thanks.
Esp8266 - master expressif
```
String CoolFileSystem::getSavedLogAsString(int num) {
  char path[32];
  String data;
  DynamicJsonDocument document;
  snprintf(path, 32, "/log/%d.json", num);
  File f = SPIFFS.open(path, "r");

  if (!f) {
    ERROR_VAR("Failed to data file:", path);
    return data;
  }
  deserializeMsgPack(document, f);
  serializeJson(document, data);
  DEBUG_VAR("Read data file:", path);
  DEBUG_VAR("Data file content:", data);
  f.close();
  yield();
  return data;
}
```
my file : 
```
��state��reported��timestamp�2018-06-29T14:17:11Z�mac�2C3AE84FC076�firmwareVersion�v0.2.6-2-g0ea852c�visibleLight�infraRed�ultraViolet�Temperature�Pressure�Humidity�Vbat�soilMoisture�ActB
```

my serial output : 
```
DEBUG: Data file content: {}
DEBUG: Saved JSON data to send: {}
```

**Comment by trap98** [comment]
Ok so, I tried a lot of things.
* My first problem : I don't know if you volontary add and don't replace but isn't intuitive for me
 ```
int main()
{
  DynamicJsonDocument doc;
  std::string data = "{\"state\":{\"reported\":{\"timestamp\":\"2018-07-02T09:40:12Z\"}}}";
  deserializeJson(doc, data);
  serializeMsgPack(doc, data);
  std::cout << data << std::endl;
  return 0;
}
```
output :
```
{"state":{"reported":{"timestamp":"2018-07-02T09:40:12Z"}}}��state��reported��timestamp�2018-07-02T09:40:12Z
```

* My second problem : I don't know how break your function but with my json deserialization don't work.
with my big json :
```
int main()
{
  DynamicJsonDocument doc;
  std::string data = "{\"state\":{\"reported\":{\"timestamp\":\"2018-07-02T09:40:12Z\",\"mac\":\"2C3AE84FC076\",\"firmwareVersion\":\"v0.2.7-5-gf4d4d78\",\"visibleLight\":261,\"infraRed\":255,\"ultraViolet\":0.02,\"Temperature\":26.63,\"Pressure\":101145.7,\"Humidity\":54.79883,\"Vbat\":4.171261,\"soilMoisture\":0,\"ActB\":0}}}";
  deserializeJson(doc, data);
  data = "";
  serializeMsgPack(doc, data);
  std::cout << data << std::endl;
  DynamicJsonDocument doc2;
  std::cout << deserializeMsgPack(doc2, data).c_str() << std::endl;
  serializeJson(doc2, std::cout);

  return 0;
}
```
output :
```
��state��reported��timestamp�2018-07-02T09:40:12Z�mac�2C3AE84FC076�firmwareVersion�v0.2.7-5-gf4d4d78�visibleLight�infraRed�ultraViolet�Temperature�Pressure�Humidity�Vbat�soilMoisture�ActB
IncompleteInput
{}
```
with random little json :
```
int main()
{
  DynamicJsonDocument doc;
  std::string data = "{\"state\":{\"reported\":{\"timestamp\":\"2018-07-02T09:40:12Z\"}}}";
  deserializeJson(doc, data);
  data = "";
  serializeMsgPack(doc, data);
  std::cout << data << std::endl;
  DynamicJsonDocument doc2;
  std::cout << deserializeMsgPack(doc2, data).c_str() << std::endl;
  serializeJson(doc2, std::cout);

  return 0;
}
```
output :
```
��state��reported��timestamp�2018-07-02T09:40:12Z
Ok
{"state":{"reported":{"timestamp":"2018-07-02T09:40:12Z"}}}
```

**Comment by bblanchon** [comment]
Hi @trap98,

> My first problem : I don't know if you volontary add and don't replace but isn't intuitive for me

The library (not me) appends to the end of the string to be consistent with streams. 
Admittedly, `deserializeJson(doc, data); serializeMsgPack(doc, data);` is not a common pattern.

> My second problem : I don't know how break your function but with my json deserialization don't work.

Indeed, this is a bug.
Due to the lazy parsing of integers, ArduinoJson is currently not able to chain `deserializeJson()` and `serializeMsgPack()`.

Regards,
Benoit

**Comment by bblanchon** [comment]
Fix is available in [v6.2.0-beta](https://github.com/bblanchon/ArduinoJson/releases/tag/v6.2.0-beta)

**Comment by trap98** [comment]
Thanks

**Comment by trap98** [comment]
Salut @bblanchon ,
I don't know if you forgot to add something in the release note, but 6.2.0 destroy everything for me.
```
In file included from src/core/CoolBoard.cpp:29:0:
src/core/CoolConfig.h: In static member function 'static void CoolConfig::set(ArduinoJson::JsonObject&, const char*, T&, bool)':
src/core/CoolConfig.h:44:33: error: 'class ArduinoJson::Internals::JsonObjectSubscript<const char*>' has no member named 'success'
if (!overwrite && json[key].success()) {
^
src/core/CoolConfig.h: In static member function 'static void CoolConfig::setArray(ArduinoJson::JsonObject&, const char*, uint8_t, T&, bool)':
src/core/CoolConfig.h:52:36: error: 'class ArduinoJson::Internals::JsonArraySubscript' has no member named 'success'
if (!overwrite && json[key][i].success()) {
^
src/core/CoolBoard.cpp: In member function 'void CoolBoard::loop()':
src/core/CoolBoard.cpp:108:43: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::Internals::enable_if<true, ArduinoJson::JsonObject>::type {aka ArduinoJson::JsonObject}'
JsonObject &root = doc.to<JsonObject>();
^
src/core/CoolBoard.cpp:109:56: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::JsonObject'
JsonObject &state = root.createNestedObject("state");
^
src/core/CoolBoard.cpp:110:63: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::JsonObject'
JsonObject &reported = state.createNestedObject("reported");
^
src/core/CoolBoard.cpp: In member function 'bool CoolBoard::config()':
src/core/CoolBoard.cpp:244:47: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::Internals::JsonVariantAs<ArduinoJson::JsonObject>::type {aka ArduinoJson::JsonObject}'
JsonObject  &json = document.as<JsonObject>();
^
src/core/CoolBoard.cpp: In member function 'void CoolBoard::update(const char*)':
src/core/CoolBoard.cpp:271:41: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::Internals::JsonVariantAs<ArduinoJson::JsonObject>::type {aka ArduinoJson::JsonObject}'
JsonObject &root = doc.as<JsonObject>();
^
src/core/CoolBoard.cpp:272:35: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::Internals::JsonObjectSubscript<const char*>'
JsonObject &state = root["state"];
^
src/core/CoolBoard.cpp:273:13: error: 'class ArduinoJson::JsonObject' has no member named 'success'
if (state.success()) {
^
src/core/CoolBoard.cpp:275:38: error: 'ArduinoJson::Internals::enable_if<true, ArduinoJson::Internals::JsonObjectSubscript<const char*> >::type' has no member named 'success'
if (state["CoolBoard"]["manual"].success()) {
^
src/core/CoolBoard.cpp:279:67: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::Internals::enable_if<true, ArduinoJson::Internals::JsonObjectSubscript<const char*> >::type {aka ArduinoJson::Internals::JsonObjectSubscript<const char*>}'
JsonObject &firmwareJson = state["CoolBoard"]["firmwareUpdate"];
^
src/core/CoolBoard.cpp:280:22: error: 'class ArduinoJson::JsonObject' has no member named 'success'
if (firmwareJson.success()) {
^
src/core/CoolBoard.cpp:334:43: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::Internals::enable_if<true, ArduinoJson::JsonObject>::type {aka ArduinoJson::JsonObject}'
JsonObject& root = doc.to<JsonObject>();
^
src/core/CoolBoard.cpp:335:56: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::JsonObject'
JsonObject &state = root.createNestedObject("state");
^
src/core/CoolBoard.cpp:337:38: error: 'RawJson' was not declared in this scope
state["desired"] = RawJson("null");
^
src/core/CoolBoard.cpp: In member function 'void CoolBoard::sendConfig(const char*, const char*)':
src/core/CoolBoard.cpp:414:41: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::Internals::enable_if<true, ArduinoJson::JsonObject>::type {aka ArduinoJson::JsonObject}'
JsonObject &root = doc.to<JsonObject>();
^
src/core/CoolBoard.cpp:415:54: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::JsonObject'
JsonObject &state = root.createNestedObject("state");
^
src/core/CoolBoard.cpp:416:61: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::JsonObject'
JsonObject &reported = state.createNestedObject("reported");
^
src/core/CoolBoard.cpp: In member function 'void CoolBoard::tryFirmwareUpdate()':
src/core/CoolBoard.cpp:629:43: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::Internals::JsonVariantAs<ArduinoJson::JsonObject>::type {aka ArduinoJson::JsonObject}'
JsonObject &root = doc.as<JsonObject>();
^
src/core/CoolBoard.cpp:636:40: error: 'class ArduinoJson::Internals::JsonObjectSubscript<const char*>' has no member named 'success'
if (root["firmwareUrlFingerprint"].success() &&
^
src/core/CoolBoard.cpp:637:29: error: 'class ArduinoJson::Internals::JsonObjectSubscript<const char*>' has no member named 'success'
root["firmwareUrl"].success() && root["firmwareVersion"].success()) {
^
src/core/CoolBoard.cpp:637:66: error: 'class ArduinoJson::Internals::JsonObjectSubscript<const char*>' has no member named 'success'
root["firmwareUrl"].success() && root["firmwareVersion"].success()) {
^
src/core/CoolBoard.cpp: In member function 'void CoolBoard::updateFirmware(String, String, String)':
src/core/CoolBoard.cpp:666:75: warning: 't_httpUpdate_return ESP8266HTTPUpdate::update(const String&, const String&, const String&, bool)' is deprecated (declared at /Users/Gbradel/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h:76) [-Wdeprecated-declarations]
ESPhttpUpdate.update(firmwareUrl, "", firmwareUrlFingerprint, true);
^
src/core/CoolBoard.cpp:667:12: warning: enumeration value 'HTTP_UPDATE_NO_UPDATES' not handled in switch [-Wswitch]
switch (ret) {
^
*** [.pioenvs/debug/libe78/core/CoolBoard.cpp.o] Error 1
In file included from src/core/CoolBoardActuator.cpp:27:0:
src/core/CoolConfig.h: In static member function 'static void CoolConfig::set(ArduinoJson::JsonObject&, const char*, T&, bool)':
src/core/CoolConfig.h:44:33: error: 'class ArduinoJson::Internals::JsonObjectSubscript<const char*>' has no member named 'success'
if (!overwrite && json[key].success()) {
^
src/core/CoolConfig.h: In static member function 'static void CoolConfig::setArray(ArduinoJson::JsonObject&, const char*, uint8_t, T&, bool)':
src/core/CoolConfig.h:52:36: error: 'class ArduinoJson::Internals::JsonArraySubscript' has no member named 'success'
if (!overwrite && json[key][i].success()) {
^
src/core/CoolBoardActuator.cpp: In member function 'bool CoolBoardActuator::doAction(ArduinoJson::JsonObject&, uint8_t, uint8_t)':
src/core/CoolBoardActuator.cpp:63:37: error: 'class ArduinoJson::Internals::JsonObjectSubscript<const String&>' has no member named 'success'
if (root[this->primaryType].success()) {
^
src/core/CoolBoardActuator.cpp:73:37: error: 'class ArduinoJson::Internals::JsonObjectSubscript<const String&>' has no member named 'success'
if (root[this->primaryType].success()) {
^
src/core/CoolBoardActuator.cpp:82:37: error: 'class ArduinoJson::Internals::JsonObjectSubscript<const String&>' has no member named 'success'
if (root[this->primaryType].success()) {
^
src/core/CoolBoardActuator.cpp:92:37: error: 'class ArduinoJson::Internals::JsonObjectSubscript<const String&>' has no member named 'success'
if (root[this->primaryType].success()) {
^
src/core/CoolBoardActuator.cpp:105:35: error: 'class ArduinoJson::Internals::JsonObjectSubscript<const String&>' has no member named 'success'
if (root[this->primaryType].success()) {
^
src/core/CoolBoardActuator.cpp: In member function 'bool CoolBoardActuator::config()':
src/core/CoolBoardActuator.cpp:125:46: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject&' from an rvalue of type 'ArduinoJson::Internals::JsonVariantAs<ArduinoJson::JsonObject>::type {aka ArduinoJson::JsonObject}'
JsonObject &json = document.as<JsonObject>();
^
*** [.pioenvs/debug/libe78/core/CoolBoardActuator.cpp.o] Error 1
```

**Comment by trap98** [comment]
I know i need to replace my ``` RawJson ``` but this break my program before

**Comment by bblanchon** [comment]
[References were removed in 6.1.0](https://arduinojson.org/2018/07/02/version-6-1-0/?utm_source=github&utm_medium=issues)

**Comment by trap98** [comment]
Thanks, and sorry for that
